### ISSUE TITLE
 undefined reference to `ngx_udp_connect' nginx 1.12.0 error

### ISSUE THREAD

**Issue by xianhuawei** [zebrafishlabs/nginx-statsd#28]
objs/addon/nginx-statsd-master/ngx_http_statsd.o: In function `ngx_http_statsd_udp_send':
/tmp/soft/nginx-statsd-master/ngx_http_statsd.c:367: undefined reference to `ngx_udp_connect'
collect2: ld returned 1 exit status

**Comment by peterdk** [comment]
https://trac.nginx.org/nginx/ticket/1244
but won't be fixed by NGINX.

**Comment by peterdk** [comment]
Applying the patch.diff to NGINX from the linked trac ticket fixes the issue though. I compiled 1.13.0 with it properly. And the statsd implementation is working fine.

**Comment by polynomial** [comment]
thank you @peterdk for the pointer, sad about the upstream lameness. ):

**Comment by BenMusch** [comment]
~~Still having this issue after applying the patch on 1.17.3 -- anyone else experiencing this on that version?~~

Nevermind, the problem was my build script over-writing nginx source after applying the patch
